server:
  port: 8080
spring:
  application:
    name: reggie_backend
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://120.46.214.246:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: cry020114
  redis:
    host: 120.46.214.246
    port: 6379
    database: 0
    jedis:
      pool:
        max-wait: 1ms
        max-active: 8
        max-idle: 8
        min-idle: 0
  cache:
    redis:
      time-to-live: 1800000
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  #  path: D:/SSMLearning/ProReggie/reggie_backend/imgResource/
  path: /opt/food_images/